export const baseUrl = 'http://m.xueerqin.net'
export const baseUrl2 = 'https://srv.xueerqin.net/public-api'
export const baseUrlSet = 'http://srv.xueerqin.net/apiV2-stucard'
export const baseUrlCheking = 'http://srv.xueerqin.net/api-schoolmanage'
export const clockIn = 'http://srv.xueerqin.net/api-attendance'
export const circle = 'http://srv.xueerqin.net/api-classboard-show'
export const giveALike = 'http://srv.xueerqin.net/api-thumbup'
export const sure = 'http://srv.xueerqin.net/api-attendance'
export const commentUrl = 'http://srv.xueerqin.net/api-comment'
export const studentNameUrl = 'http://srv.xueerqin.net/api-attendance'
export const homeWorkUrl = 'http://srv.xueerqin.net/api-homework'
export const publicUrl = 'http://srv.xueerqin.net/public-api'
export const noticeUrl = 'http://srv.xueerqin.net/api-classnotice'
export const partyBuildUrl = 'http://srv.xueerqin.net/api-partybuild'
export const examUrl = 'http://srv.xueerqin.net/api-schoolmanage'
export const fytestUrl = 'http://t-api.fytest.xueerqin.net'
// export const homeWorkUrl2 = 'http://api-homework.xueerqin.net'
// export const noticeUrl2 = 'http://api-classnotice.xueerqin.net'
export const appUrl = 'http://tapp.xueerqin.net'
export const payrollUrl = 'http://srv.xueerqin.net/api-oa-salary'
export const oaUrl = 'http://srv.xueerqin.net/api-oa-flow'
export const oaNoticeUrl = 'http://srv.xueerqin.net/api-classnotice'
export const formUrl = 'http://srv.xueerqin.net/api-oa-form'
export const organizationUrl = 'http://srv.xueerqin.net/api-oa-dept'
export const kitchenUrl = 'http://192.168.66.218:9101/kitchen-center'
export const schoolUrl = appUrl


